# Generated by Django 3.1.4 on 2022-07-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetails',
            old_name='email',
            new_name='username',
        ),
    ]
